/* Automatically generated by chibi-ffi; version: 0.4 */

#include <chibi/eval.h>
/*
types: (point)
enums: ()
*/


sexp sexp_init_library (sexp ctx, sexp self, sexp_sint_t n, sexp env, const char* version, const sexp_abi_identifier_t abi) {
  sexp sexp_point_type_obj;
  sexp_gc_var3(name, tmp, op);
  if (!(sexp_version_compatible(ctx, version, sexp_version)
        && sexp_abi_compatible(ctx, abi, SEXP_ABI_IDENTIFIER)))
    return SEXP_ABI_ERROR;
  sexp_gc_preserve3(ctx, name, tmp, op);
  name = sexp_c_string(ctx, "point", -1);
  sexp_point_type_obj = sexp_register_c_type(ctx, name, sexp_finalize_c_type);
  tmp = sexp_string_to_symbol(ctx, name);
  sexp_env_define(ctx, env, tmp, sexp_point_type_obj);
  sexp_type_slots(sexp_point_type_obj) = SEXP_NULL;
  sexp_push(ctx, sexp_type_slots(sexp_point_type_obj), sexp_intern(ctx, "y", -1));
  sexp_push(ctx, sexp_type_slots(sexp_point_type_obj), sexp_intern(ctx, "x", -1));
  sexp_type_getters(sexp_point_type_obj) = sexp_make_vector(ctx, SEXP_TWO, SEXP_FALSE);
  sexp_type_setters(sexp_point_type_obj) = sexp_make_vector(ctx, SEXP_TWO, SEXP_FALSE);
  sexp_gc_release3(ctx);
  return SEXP_VOID;
}

